services:

  pypah-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: pypah-dev
    volumes:
      - ./ETL:/app/ETL
      - ./Streamlit:/app/Streamlit
    ports:
      - "8502:8501"
    stdin_open: true
    tty: true

  pypah-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: pypah-api
    ports:
      - "8000:8000"
    env_file:
      - .env

  pypah-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    container_name: pypah-app
    ports:
      - "8501:8501"
    volumes:
      - ./Streamlit:/app/Streamlit
    env_file:
      - .env
    depends_on:
      - pypah-api