FROM python:3.11-slim

WORKDIR /app

# Dependências de sistema necessárias pro PySUS / dbfread
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2 \
    libxml2-dev \
    libxslt1-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements_dev.txt .
RUN pip install --no-cache-dir -r requirements_dev.txt

COPY . .

CMD ["bash"]