FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements_dash.txt .
RUN pip install --no-cache-dir -r requirements_dash.txt

COPY . /app

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "Streamlit/dash_PyPAH.py", "--server.port=8501", "--server.address=0.0.0.0"]
